- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: uninstall nginx
    apt:
      name: nginx
      state: ansent
      update_cache: true
    register: valnot1
    failed_when: valnot1.cache_update_time > 1

  